PERI_Project/Controllers/Owner/productController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PERI_Project.Models;
using System.IO;
namespace PERI_Project.Controllers.Owner
{
    public class productController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: product
        public ActionResult Index()
        {
            return View(db.tbl_product.ToList());
        }

        // GET: product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_product);
        }

        // GET: product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "pk_id_product,product_name,product_price")]*/ tbl_product tbl_product)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        string fileName = Path.GetFileNameWithoutExtension(tbl_product.ImageFile.FileName);
                        string extension = Path.GetExtension(tbl_product.ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        tbl_product.ImagePath = "~/Content/images/products/" /*+foldername+"/"*/+ fileName;
                        fileName = Path.Combine(Server.MapPath("~/Content/images/products/"), fileName);
                        tbl_product.ImageFile.SaveAs(fileName);
                        db.tbl_product.Add(tbl_product);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        ViewData["error"] = ex.Message;
                    }
                }
            }
            return View(tbl_product);
        }

        // GET: product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_product);
        }

        // POST: product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "pk_id_product,product_name,product_price")]*/ tbl_product tbl_product)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        string fileName = Path.GetFileNameWithoutExtension(tbl_product.ImageFile.FileName);
                        string extension = Path.GetExtension(tbl_product.ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        tbl_product.ImagePath = "~/Content/images/products/" /*+foldername+"/"*/+ fileName;
                        fileName = Path.Combine(Server.MapPath("~/Content/images/products/"), fileName);
                        tbl_product.ImageFile.SaveAs(fileName);
                        db.Entry(tbl_product).State = EntityState.Modified;
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        ViewData["error"] = ex.Message;
                    }
                }
            }
            return View(tbl_product);
        }

        // GET: product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_product tbl_product = db.tbl_product.Find(id);
            if (tbl_product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_product);
        }

        // POST: product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    tbl_product tbl_product = db.tbl_product.Find(id);
                    db.tbl_product.Remove(tbl_product);
                    db.SaveChanges();
                    transaction.Commit();
                    
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ViewData["error"] = ex.Message;
                }
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PERI_Project/Views/product/Create.cshtml
@model PERI_Project.Models.tbl_product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h4>Create Product</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.product_name, "Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.product_price, "Product Price", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.product_price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath, "Product Image", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
<div class="container">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PERI_Project/Views/product/Delete.cshtml
@model PERI_Project.Models.tbl_product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Delete Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Product Name
                @*@Html.DisplayNameFor(model => model.product_name)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_name)
            </dd>

            <dt>
                Product Price
                @*@Html.DisplayNameFor(model => model.product_price)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product_price)
            </dd>

        </dl>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

PERI_Project/Views/product/Details.cshtml
@model PERI_Project.Models.tbl_product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">
        <h4>Detail Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Product Image
                @*@Html.DisplayNameFor(model => model.product_name)*@
            </dt>
            <dd>
                <img src="@Url.Content(Model.ImagePath)" width="250" height="250" multiple />
            </dd>

            <dt>
                Product Name
                @*@Html.DisplayNameFor(model => model.product_name)*@
            </dt>
            <dd>
                @Html.DisplayFor(model => model.product_name)
            </dd>

            <dt>
                Product Price
                @*@Html.DisplayNameFor(model => model.product_price)*@
            </dt>
            <dd>
                @Html.DisplayFor(model => model.product_price)
            </dd>

        </dl>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.pk_id_product }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>

PERI_Project/Views/product/Edit.cshtml
@model PERI_Project.Models.tbl_product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-horizontal">
            <h4>Edit Product</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.pk_id_product)

            <div class="form-group">
                @Html.LabelFor(model => model.product_name, "Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.product_price, "Product Price", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.product_price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath, "Product Image", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
<div class="container">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PERI_Project/Views/product/Index.cshtml
@model IEnumerable<PERI_Project.Models.tbl_product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.product_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_price)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.pk_id_product }) |
                @Html.ActionLink("Details", "Details", new { id=item.pk_id_product }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.pk_id_product })
            </td>
        </tr>
    }

    </table>*@
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Data Product</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Product Price</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Product Name</th>
                        <th>Product Price</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.product_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.product_price)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.pk_id_product }) |
                                @Html.ActionLink("Details", "Details", new { id = item.pk_id_product }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.pk_id_product })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>