PERI_Project/Controllers/Admin/orderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using PERI_Project.Models;

namespace PERI_Project.Controllers.Admin
{
    public class orderController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: order
        public ActionResult Index()
        {
            var tbl_order = db.tbl_order.Include(t => t.tbl_customerOrder).Include(t => t.tbl_design).Include(t => t.tbl_product);
            return View(tbl_order.ToList());
        }

        // GET: order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            return View(tbl_order);
        }

        // GET: order/Create
        public ActionResult Create()
        {
            tbl_customerOrder customerOrder = Session["Customer"] as tbl_customerOrder;
            tbl_order order = new tbl_order();
            order.fk_customer_id = customerOrder.pk_id_customerOrder;
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty");
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name");
            return View(order);

        }

        // POST: order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pk_id_order,fk_customer_id,details_order,lenght_meter,width_meter,fk_design_id,fk_product_id,amount,price,date,order_status")] tbl_order order_table)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        order_table.order_status = "Not Yet";
                        db.tbl_order.Add(order_table);
                        order_table.date = DateTime.Now;
                        tbl_design design = db.tbl_design.Find(order_table.fk_design_id);
                        tbl_product product = db.tbl_product.Find(order_table.fk_product_id);
                        order_table.price = (order_table.lenght_meter * order_table.width_meter * product.product_price + design.design_price) * order_table.amount;
                        db.tbl_order.Add(order_table);
                        db.SaveChanges();
                        tbl_payment total = new tbl_payment();
                        total.fk_id_customerOrder = order_table.fk_customer_id;
                        double? totalprice = db.tbl_order.Where(item => item.fk_customer_id == total.fk_id_customerOrder).Select(item => item.price).DefaultIfEmpty().Sum();
                        total.order_status = "Not Yet";
                        total.total_price = totalprice;
                        total.payment_status = "Not Yet";
                        db.tbl_payment.Add(total);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index", "payment");

                    }
                    catch (Exception ex) { transaction.Rollback(); ViewData["Data"] = ex.Message; }
                }

            }
     
  

            ViewBag.fk_customer_id = new SelectList(db.tbl_customerOrder, "pk_id_customerOrder", "name", order_table.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", order_table.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", order_table.fk_product_id);
            return View(order_table);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnotherOrder([Bind(Include = "pk_id_order,fk_customer_id,details_order,lenght_meter,width_meter,fk_design_id,fk_product_id,amount,price,date,order_status")] tbl_order order_table)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        order_table.date = DateTime.Now;
                        order_table.order_status = "Not Yet";
                        db.tbl_order.Add(order_table);
                        tbl_design design = db.tbl_design.Find(order_table.fk_design_id);
                        tbl_product product = db.tbl_product.Find(order_table.fk_product_id);
                        order_table.price = (order_table.lenght_meter * order_table.width_meter * product.product_price + design.design_price) * order_table.amount;
                        db.tbl_order.Add(order_table);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Create");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback(); ViewData["Data"] = ex.Message;
                    }
                }

            }
            
            //ViewBag.fk_customer_id = new SelectList(db.customers, "pk_id_customer", "name", order_table.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", order_table.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", order_table.fk_product_id);
            return View(order_table);
        }




        // GET: order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_customer_id = new SelectList(db.tbl_customerOrder, "pk_id_customerOrder", "name", tbl_order.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", tbl_order.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", tbl_order.fk_product_id);
            return View(tbl_order);
        }

        // POST: order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "pk_id_order,fk_customer_id,details_order,lenght_meter,width_meter,fk_design_id,fk_product_id,amount,price,date,order_status,ImagePath")]*/ tbl_order tbl_order)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        string fileName = Path.GetFileNameWithoutExtension(tbl_order.ImageFile.FileName);
                        string extension = Path.GetExtension(tbl_order.ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        tbl_order.ImagePath = "~/Content/images/order_design/" /*+foldername+"/"*/+ fileName;
                        fileName = Path.Combine(Server.MapPath("~/Content/images/order_design/"), fileName);
                        tbl_order.ImageFile.SaveAs(fileName);
                        db.Entry(tbl_order).State = EntityState.Modified;
                        db.SaveChanges();
                        transaction.Commit();
                        ModelState.Clear();
                        return RedirectToAction("Index","payment");

                    }
                    catch (Exception ex) { transaction.Rollback(); ViewData["Data"] = ex.Message; }
                }

            }
     
           
            ViewBag.fk_customer_id = new SelectList(db.tbl_customerOrder, "pk_id_customerOrder", "name", tbl_order.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", tbl_order.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", tbl_order.fk_product_id);
            return View(tbl_order);
        }

        [HttpGet]
        public ActionResult Upload(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order order_table = db.tbl_order.Find(id);
            if (order_table == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_customer_id = new SelectList(db.tbl_customerOrder, "pk_id_customerOrder", "name", order_table.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", order_table.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", order_table.fk_product_id);
            return View(order_table);
        }

        [HttpPost]
        public ActionResult Upload(tbl_order imageModel)
        {
            //Directory.CreateDirectory(@"~/Image/" + foldername);

PERI_Project/Views/order/Create.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPageEmployee.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.fk_customer_id, "customer Order id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fk_customer_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.fk_customer_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.details_order, "Details Order", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.details_order, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.details_order, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lenght_meter, "Length (Meter)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lenght_meter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lenght_meter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.width_meter, "Width (Meter)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.width_meter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.width_meter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fk_design_id, "Design Difficulty", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("fk_design_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.fk_design_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fk_product_id, "Product", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("fk_product_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.fk_product_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.order_status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.order_status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.order_status, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Another Order" formmethod="post" formaction="@Url.Action("AnotherOrder","order")" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PERI_Project/Views/order/Delete.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPageEmployee.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Details Order
            @*@Html.DisplayNameFor(model => model.details_order)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.details_order)
        </dd>

        <dt>
            Length (meter)
            @*@Html.DisplayNameFor(model => model.lenght_meter)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lenght_meter)
        </dd>

        <dt>
            Width (meter)
            @*@Html.DisplayNameFor(model => model.width_meter)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.width_meter)
        </dd>

        <dt>
            Amount
            @*@Html.DisplayNameFor(model => model.amount)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            Price
            @*@Html.DisplayNameFor(model => model.price)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            Date
            @*@Html.DisplayNameFor(model => model.date)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            Order Status
            @*@Html.DisplayNameFor(model => model.order_status)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_status)
        </dd>

        <dt>
            Name
            @*@Html.DisplayNameFor(model => model.tbl_customerOrder.name)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_customerOrder.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_design.difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_design.difficulty)
        </dd>

        <dt>
            Product Name
            @*@Html.DisplayNameFor(model => model.tbl_product.product_name)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_product.product_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PERI_Project/Views/order/Details.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPageEmployee.cshtml";
}

<h2>Details</h2>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img src="@Url.Content(Model.ImagePath)" width="250" height="250" multiple />
        </dd>
    </dl>
</div>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Details Order
            @*@Html.DisplayNameFor(model => model.details_order)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.details_order)
        </dd>

        <dt>
            Length (meter)
            @*@Html.DisplayNameFor(model => model.lenght_meter)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lenght_meter)
        </dd>

        <dt>
            Width (meter)
            @*@Html.DisplayNameFor(model => model.width_meter)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.width_meter)
        </dd>

        <dt>
            Amount
            @*@Html.DisplayNameFor(model => model.amount)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            Price
            @*@Html.DisplayNameFor(model => model.price)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            Date
            @*@Html.DisplayNameFor(model => model.date)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            Order Status
            @*@Html.DisplayNameFor(model => model.order_status)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_status)
        </dd>

        <dt>
            Name
            @*@Html.DisplayNameFor(model => model.tbl_customerOrder.name)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_customerOrder.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_design.difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_design.difficulty)
        </dd>

        <dt>
            Product Name
            @*@Html.DisplayNameFor(model => model.tbl_product.product_name)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_product.product_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index","payment",new { },new { })
</p>

PERI_Project/Views/order/Edit.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageEmployee.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "order", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.pk_id_order)

    <div class="form-group">
        @Html.LabelFor(model => model.fk_customer_id, "Customer ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("fk_customer_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.fk_customer_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.details_order, "Details Order", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.details_order, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.details_order, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lenght_meter, "Length (meter)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lenght_meter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lenght_meter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.width_meter, "Width (meter)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.width_meter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.width_meter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fk_design_id, "Difficulty", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("fk_design_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.fk_design_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fk_product_id, "Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("fk_product_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.fk_product_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.amount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, "Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.order_status, "Order Status", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.order_status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.order_status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, "Upload Image", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PERI_Project/Views/order/Upload.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_LayoutPageEmployee.cshtml";
}

<h2>Upload</h2>


@using (Html.BeginForm("Upload", "order", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>tbl_order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.pk_id_order)
    @Html.HiddenFor(model => model.fk_customer_id)
    @Html.HiddenFor(model => model.details_order)
    @Html.HiddenFor(model => model.lenght_meter)
    @Html.HiddenFor(model => model.width_meter)
    @Html.HiddenFor(model => model.fk_design_id)
    @Html.HiddenFor(model => model.fk_product_id)
    @Html.HiddenFor(model => model.amount)
    @Html.HiddenFor(model => model.price)
    @Html.HiddenFor(model => model.date)
    @Html.HiddenFor(model => model.order_status)

    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}